fail testexamplescomplete when testexamples failed

diff --git a/.github/workflows/test-examples-template.yml b/.github/workflows/test-examples-template.yml
--- a/.github/workflows/test-examples-template.yml
+++ b/.github/workflows/test-examples-template.yml
@@ -166,8 +166,14 @@ jobs:
   # We can use it for PR validation to ensure all examples have completed.
   testexamplescomplete:
 #    if: failure() != true && github.event.repository.name != 'terraform-azurerm-avm-template' && github.event.pull_request.head.repo.fork == false
-    if: always() && !failure() && !cancelled() && github.event.repository.name != 'terraform-azurerm-avm-template' && github.event.pull_request.head.repo.fork == false
+    if: github.event.repository.name != 'terraform-azurerm-avm-template' && github.event.pull_request.head.repo.fork == false
     runs-on: ubuntu-latest
-    needs: [testexamples]
+    needs: testexamples
     steps:
-      - run: echo "All tests passed"
+      - run: |
+          if [ "${{ needs.testexamples.result }}" != "success" ]; then
+            echo "Some tests failed"
+            exit 1
+          else
+            echo "All tests passed"
+          fi
